### ISSUE TITLE
Change context close to a down arrow

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#106]
<img width="405" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/b377812b-8a28-4ad6-b6d2-240d0ba77260">

The X for "gopool.go" means to remove it. So, users may mistake the upper-right X as remove all contexts. Actually, it only means closing the current window. It is better to replace X with a down arrow to mean putting it back.

**Comment by runjinz** [comment]
Replace icon from close to down arrow.
![image](https://github.com/devchat-ai/devchat/assets/12482039/2db93d8c-d588-4003-ab58-08c3a1af5adb)
