### ISSUE TITLE
Scroll left and right on code contexts

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#107]
<img width="391" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/d79dfa54-d576-4f54-a1c8-96ae2c908757">

I cannot see the full code of long lines. Is it possible to support scroll left and right?

**Comment by runjinz** [comment]
Add x scrollbar.
![image](https://github.com/devchat-ai/devchat/assets/12482039/a992fd65-40c5-4992-aa43-cfb896a8adb9)
