### ISSUE TITLE
Remove icons from commands

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#109]
<img width="286" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/5102e5b9-bdb5-4968-b7f9-e6e7857c99a8">

Two reasons:
- When the description is long (that is necessary for user's understanding even though we've tried best to shorten it), the above screenshot shows extra lines. A simple solution is to just remove icons.
- Users now can extend commands. It is a burden for them to specify icons.

**Comment by runjinz** [comment]
Already removed. Long text will now wrap to fit the width and break into a new line as needed.
![image](https://github.com/devchat-ai/devchat/assets/12482039/84774243-603d-4df6-b68f-b9a4fca66e4c)
