### ISSUE TITLE
Cannot set DevChat Access Key

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#131]
The buttons lead me to nowhere...

<img width="994" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/5da572e2-51eb-4dc2-b0d0-0b5836dad023">

**Comment by basicthinker** [comment]
<img width="947" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/4e23d948-ae2f-432c-a288-1ded9cd4735b">

This screenshot may show the problem more clearly.

**Comment by basicthinker** [comment]
@yangbobo2021  After inputing the DevChat access key in the Command Palette, the check still fails and the key doesn't work.

![807d93b0-9201-40de-bf0d-66a2042a902c](https://github.com/devchat-ai/devchat/assets/592493/5d9af3bd-5803-438a-acba-2e4674864921)

**Comment by basicthinker** [comment]
Resolved in devchat-vscode v0.1.30

**Comment by katelynn620** [comment]
It seems to have happened again. Now, when I click the button, the input key dialog doesn't appear. The version is the latest one, v0.1.32.
