### ISSUE TITLE
Is it possible to change the URL of the OpenAI API server to my own forwarding service URL, for example, changing ‘api.openai.com' to 'mydomain.com'?

### ISSUE THREAD

**Issue by edisonzf2020** [devchat-ai/devchat#138]
**Is your feature request related to a problem? Please describe.**
Because mainland China cannot directly access OpenAI's API server, I have been using a forwarding server.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by basicthinker** [comment]
@edisonzf2020 you could set your environment variable `OPENAI_API_BASE` locally and redirect the underlying requests of DevChat to your proxy. Let us know if you meet any problems that way. Note that this setting only applies if you choose GPT models. (Other models will still use our DevChat proxy. Of course, you can also use the DevChat proxy to access OpenAI models - www.devchat.ai)

**Comment by edisonzf2020** [comment]
I tried to add environment variables in the `settings.json` file under the `.vscode` directory of my VSCode project. The format is as follows:

```json
{
    "terminal.integrated.env.windows": {
        "OPENAI_API_BASE": "BASE_URL=https://mydomain.com"
    }
}
```

I made sure that the domain name of my forwarding server is correct, but it didn't work. I'm not sure what the correct way to set environment variables in VSCode is. Could you please guide me? Thank you.

**Comment by basicthinker** [comment]
@edisonzf2020 Hi, we've added settings for this case. Open the Settings page and search "devchat", as below.

<img width="849" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/5724da52-6a47-45b2-989b-c7a6e6c4d9f8">

First, set the provider of GPT models to "openai".
Then, set the base_api of the provider openai to what you want.
