### ISSUE TITLE
Show the reasons why DevChat log cannot be inserted

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#149]
<img width="460" alt="wecom-temp-40919-b80e3cc8c451021c0642d9b115233600" src="https://github.com/devchat-ai/devchat/assets/592493/167ea8b5-2bfb-4666-9d5b-3dc03809e52b">

A user asked this question. Ideally, DevChat should report if it has right access to ~/.chat or if the disk is full, and also give instructions on how to solve the issues. Then users can fix them by themselves.

@yangbobo2021 DevChat Core should report the specific reason and pass it to IDEs.

**Comment by yangbobo2021** [comment]
这个问题的原因是：用户环境中PYTHONPATH在insert命令中没有生效，已经做了修复。理论上来说，插入日志不会遇到~/.chat目录没有权限，以及磁盘满了的情况。如果真的存在这两个情况，那么会在其他操作中早早就报错了。
