### ISSUE TITLE
Identical code in symbol references 

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#151]
<img width="545" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/b5d06140-a0bd-467e-9c2b-e7c5e81a2cf1">

When finding references of a symbol, we see duplicate reference code. The specific problem here is that the `build` folder is included. There can be several possible solutions:
- Can we exclude "build" folders? Not sure if it is easy to find all patterns of "build" folder names in different programming languages or frameworks.
- Or maybe we can just compare reference code. If some references contain the same code snippet, remove some of the references. Note that such references may not be fully identical as the command may select one or two different lines.

**Comment by yangbobo2021** [comment]
Currently, we have removed this function. How to find relative contexts is decided by workflow.
