### ISSUE TITLE
"Black screen"

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#153]
<img width="377" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/978fe274-9156-4a1a-8c60-dcc994a66703">

This shows after calling `/ask-code`.

To repeat the issue:
- Clone https://github.com/daniel-hutao/helm
- In the repo, ask `/ask-code I encountered an error during a Helm upgrade: 'Error: UPGRADE FAILED... with kind Secret'. Where in the Helm's codebase is this error generated, and what's the underlying cause?`

Note: this error occurs in many other paths. The above is just one example with constant such errors.

**Comment by basicthinker** [comment]
Add this to the prompt if the error doesn't repeat:

Error: UPGRADE FAILED: release XXXXX-helm-chart failed, and has been rolled back due to atomic being set: cannot patch "XXXXX-secret" with kind Secret:
"" is invalid: patch: Invalid value: "{"apiVersion":"v1","data":{"y_certificate":"123","y_key":"SECRET_VALUE"},"kind":"Secret","metadata":{"annotations":{"meta.helm.sh/release-name":"XXXXX-helm-chart","meta.helm.sh/release-namespace":"XXXXX"},"creationTimestamp":"2022-12-21T13:02:27Z","labels":{"app.kubernetes.io/managed-by":"Helm"},"managedFields":[{"manager":"helm","operation":"Update","apiVersion":"v1","time":"2022-12-21T13:02:27Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{},"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/managed-by":{}}},"f:type":{}}},{"manager":"Go-http-client","operation":"Update","apiVersion":"v1","time":"2022-12-25T11:55:40Z","fieldsType":"FieldsV1","fieldsV1":{"f:data":{"f:y_certificate":{},"f:y_key":{}}}}],"name":"y-secret","namespace":"XXXXX-operator","resourceVersion":"121158778","uid":"aba2ee5d-2fda-4488-a890-595959c45925"},"type":"Opaque"}": illegal base64 data at input byte 0

**Comment by runjinz** [comment]
The issue has been fixed, see details at https://github.com/devchat-ai/devchat-gui/pull/2
