### ISSUE TITLE
/commit shows empty file list

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#158]
<img width="246" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/26fbdd77-e83c-4cf3-9462-66e9f8df8e8b">

If there is no "Unstaged" files, print a "None" under it. Now it looks like the buttons are about "Unstaged", quite confusing.

**Comment by yangbobo2021** [comment]
https://github.com/devchat-ai/workflows/pull/27
