### ISSUE TITLE
[内测] 前端为checkbox提供全选/反选支持

### ISSUE THREAD

**Issue by kagami-l** [devchat-ai/devchat#172]

**Comment by basicthinker** [comment]
@runjinz should this be closed? Better to leave a comment with the PR or commit.

**Comment by runjinz** [comment]
![image](https://github.com/devchat-ai/devchat/assets/12482039/2a82b402-253b-4e2f-80e6-4c6340cbfd03)
已提供全选，再次点击可取消全选。
