### ISSUE TITLE
Redundant check marks on DevChat status

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#183]
<img width="233" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/78f84bea-47bc-4403-90ca-1822c3be4cef">

When VS Code is opened, the left check mark shows immediately and then, after one or two seconds, the right one shows. We should remove the right one.

**Comment by yangbobo2021** [comment]
The left indicates the readiness status of the devchat-core python base, while the right indicates the readiness status of the devchat-commands environment, marking two different environment information.

**Comment by yangbobo2021** [comment]
@basicthinker

**Comment by pplam** [comment]
It really confuses users, we should keep only one or separate it into two different status marks

**Comment by yangbobo2021** [comment]
Each icon has tow different status currently, not ready and ready. If put fore status on one icon, I think it will confuses users more.

> It really confuses users, we should keep only one or separate it into two different status marks

**Comment by basicthinker** [comment]
> Each icon has tow different status currently, not ready and ready. If put fore status on one icon, I think it will confuses users more.
> 
> > It really confuses users, we should keep only one or separate it into two different status marks

@yangbobo2021 but no one knows this and it is costly to inform everyone. We rarely see such a design in other apps. Can we show more details when the icon is clicked?
