### ISSUE TITLE
IntelliJ设置Access Key成功了，但必须重启才可以使用

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#187]
设置Acess Key成功后，DevChat并没有被刷新。
此时如果发送消息，则会出现报错。
![image](https://github.com/devchat-ai/devchat/assets/12482039/3ce8a857-28d2-4cd9-b18e-018131dc6caf)
![image](https://github.com/devchat-ai/devchat/assets/12482039/a14f50c0-0cdd-4876-a68f-a4f99cf34af8)

**Comment by pplam** [comment]
这个报错应该是由于前端传给后端的 model 名字不正确导致，这里 "GPT-3.5" 应该写成 "gpt-3.5-turbo"，这个 issue 就转给 @small-stone 了

**Comment by small-stone** [comment]
在 v0.1.0 已解决
