### ISSUE TITLE
上下文超限导致第二次使用/commit提交没有成功

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#189]
第一次/commit是成功的，但第二次使用/commit.zh想要生成中文提交信息时，报错了。
![image](https://github.com/devchat-ai/devchat/assets/12482039/c5f437f6-7492-4c74-aeee-b93fc8715256)

**Comment by yangbobo2021** [comment]
Discussing with Runjin, we decided that if an error is expected, it should be presented as a normal description given to the user, along with tips on how to avoid such errors. Only errors that are not anticipated and for which we do not know how to improve should be returned to the user in error form.
