### ISSUE TITLE
统一插件的Access Key命名

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#194]
JetBrains叫做API Key，但官网和VSCode都叫做Access Key。
![image](https://github.com/devchat-ai/devchat/assets/12482039/d4417864-5172-4a26-be82-52d5ff591065)

![image](https://github.com/devchat-ai/devchat/assets/12482039/675391f2-1258-4913-9d8c-3bd1531feb35)

**Comment by pplam** [comment]
在 [devchat-intellij PR#65](https://github.com/devchat-ai/devchat-intellij/pull/65) 中处理了
