### ISSUE TITLE
当Commit提交信息被改为中文时报UnicodeDecodeError

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#195]
当用户修改提交信息，改为中文时，例如图中的“提交测试”，出现UnicodeDecodeError报错。
![image](https://github.com/devchat-ai/devchat/assets/12482039/93f6f173-868b-4209-9c84-6ec851374b6d)

**Comment by yangbobo2021** [comment]
@pplam @yangbobo2021 分别进行复现，都没有复现出问题，讨论后认为应该是前边一个版本修复乱码问题已经同时修复了。
