### ISSUE TITLE
IntelliJ没有设置Key时，工作流报错体验不好

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#196]
当用户没设置Access Key，但调用工作流时，会出现报错。
![image](https://github.com/devchat-ai/devchat/assets/12482039/8d88b381-745e-417d-8f1d-06d556a075bf)
可以参考VSCode设计，对话中提示需要设置Access Key。
![image](https://github.com/devchat-ai/devchat/assets/12482039/66f32124-bd82-4b24-9b14-ba3259bb5f3a)

**Comment by pplam** [comment]
这个后端已经在 v0.0.9 改进了报错方式，但后端报错的 message 展示跟 vscode 并不是一模一样的，目前格式是这样：

<img width="455" alt="Screenshot 2024-01-23 at 10 04 52" src="https://github.com/devchat-ai/devchat/assets/12783579/bc487563-ee80-45a5-ad16-269da9e18f12">

请问 @yangbobo2021 vscode 那边是不是前端检查了没有 key 就直接显示那条消息？

**Comment by pplam** [comment]
@runjinz 如果要 intellij 的效果跟 vscode 一样，可能得 @small-stone 来前端检查下，如果没有 key，直接显示那条消息
