### ISSUE TITLE
360 antivirus clean python enviroment on windows caused errors during generate unit test.

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#201]
JetBrains also faces an older problem wherein the Python environment gets detected and obstructed by 360 antivirus, resulting in errors during unit test generation.
![image](https://github.com/devchat-ai/devchat/assets/12482039/c75c854b-c238-4290-b677-992d03643bac)
![image](https://github.com/devchat-ai/devchat/assets/12482039/b27eead7-fb63-4e34-a304-70cd1ac8f5c4)

**Comment by yangbobo2021** [comment]
Reinstall the Windows system, install 360 software, install VSCode, DevChat, and there are no files deleted by antivirus, works normally.

**Comment by runjinz** [comment]
经测试，未能再复现
