### ISSUE TITLE
The IDEA 2022.2 version cannot find the latest version (0.0.9) of devchat, it can only find 0.0.5.

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#202]
Because he couldn't install the latest 0.0.9 version, this user is still stuck with a blank screen and can't use the plugin.
![image](https://github.com/devchat-ai/devchat/assets/12482039/a610b910-8567-4cd0-b231-7fc501785a69)
![image](https://github.com/devchat-ai/devchat/assets/12482039/f9c4c919-3206-4214-a997-9f5cfae6e65f)

**Comment by basicthinker** [comment]
We require IDEA 2022.3 or above.
