### ISSUE TITLE
The workflow menu doesn't hide the /unit_tests menu in VSCode v0.1.39.

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#203]
In VSCode 0.1.39, this menu should be hidden.
![image](https://github.com/devchat-ai/devchat/assets/12482039/89adaf78-aa00-4fa2-a7f2-b3c251706597)

**Comment by yangbobo2021** [comment]
V0.1.40 will hide /unit_tests and add text button before function to call /unit_tests more easier.
