### ISSUE TITLE
Installed DevChat version 0.0.9 in Android Studio, but it shows nothing to show after launching.

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#204]
After installing DevChat 0.0.9, there's no content displayed when I launch it. My IDE is Android Studio 2022.3.1
![img_v3_027c_c024fe4c-523e-4797-aa70-85a60277c89g](https://github.com/devchat-ai/devchat/assets/12482039/60ec6431-a62d-483d-9a26-55f2af080beb)
![img_v3_027c_f3387c60-daa4-4b6f-b084-7fc92c7bab6g](https://github.com/devchat-ai/devchat/assets/12482039/6c5e7f0d-035e-4384-bca7-00186282fa0a)
![img_v3_027c_c3195643-606f-4142-8697-dad95062b36g](https://github.com/devchat-ai/devchat/assets/12482039/be897058-0bdd-4e2d-8c8c-de37480f199e)

**Comment by pplam** [comment]
Steps to enable DevChat on Android Studio:

1. Install JetBrains Runtime with JCEF：Help -> Find Action... -> Choose Boot Runtime for the IDE...
![img_v3_027f_07f9c334-23ae-43cd-99b5-d56ee6c0a35g](https://github.com/devchat-ai/devchat/assets/12783579/ab2b88d0-7994-4c96-abd3-0594949ad764)

3. Disable `ide.browser.jcef.sandbox.enable`：Help -> Find Action... -> Registry...
![img_v3_027f_d223c4e8-4f2a-462c-a77c-c001de38dadg](https://github.com/devchat-ai/devchat/assets/12783579/880f619d-7b51-403f-9845-f78915f9da5a)

5. Restart Android Studio and install DevChat
<img width="466" alt="img_v3_027f_2d971e48-969c-4fab-a041-77aae77f786g" src="https://github.com/devchat-ai/devchat/assets/12783579/17a391a9-e6bf-46f0-98aa-069f9498afa8">
