### ISSUE TITLE
IntelliJ IDEA is giving an error, ValueError: Model 'GPT-3.5' not found in /Users/xxx/.chat/config.yml

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#217]
After setting the Key, the conversation throws an error, ValueError: Model 'GPT-3.5' not found in /Users/xxx/.chat/config.yml
![image](https://github.com/devchat-ai/devchat/assets/12482039/5b30325d-709e-4b4b-8de0-fee4c4d019f9)

**Comment by small-stone** [comment]
Fixed in v0.1.0 version
