### ISSUE TITLE
I think the English prompt for an invalid key should not be "is: DC.xxxx," maybe something "like DC.xxxx" would be better

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#223]
The current prompts may be misunderstood by users, and some users may even copy this example key to configure it.
![image](https://github.com/devchat-ai/devchat/assets/12482039/8546acab-db44-4d74-ba8f-6b90144d9b5f)

**Comment by yangbobo2021** [comment]
With new configuration, user will not setting key by vscode command, so, this code will be deleted.
