### ISSUE TITLE
The user encountered an initialization error at startup, but can still have a normal conversation.

### ISSUE THREAD

**Issue by runjinz** [devchat-ai/devchat#229]
You can chat, but it throws an initialization error. 
The user is at the back, and using "Add unit tests" also gives an error, I will mention it in another issue and paste it later.
![image](https://github.com/devchat-ai/devchat/assets/12482039/e997c883-dd3d-478e-ac29-2bcc3312e04b)

**Comment by pplam** [comment]
This issue is caused by the initialization problem which was resolved, so it is resolved too.
