### ISSUE TITLE
[IntelliJ] Can't select topic from history topic list

### ISSUE THREAD

**Issue by pplam** [devchat-ai/devchat#268]
It seems that frontend doesn't pass the `topicID` to backend:

<img width="1385" alt="Screenshot 2024-02-20 at 00 07 01" src="https://github.com/devchat-ai/devchat/assets/12783579/6c2b3a40-4c8d-4171-ad09-99ccac654e2d">

**Comment by small-stone** [comment]
fix in https://github.com/devchat-ai/devchat-gui/commit/96f6f79d3c41d2920adcd5bafab06aa95c93de99
