### ISSUE TITLE
Unified Configuration Management Across IDEs

### ISSUE THREAD

**Issue by yangbobo2021** [devchat-ai/devchat#270]
## Issue Description
Currently, the configuration management for different IDEs (VSCode, JetBrains, etc.) is handled separately, without shared code logic. This approach is not conducive to code maintenance or multi-IDE platform support. Additionally, configuration display and interaction within VSCode are not user-friendly, necessitating more customized property displays to meet requirements.

To address these issues, we need to undertake four sub-tasks:

- [x] **Frontend Support**: Implement display, setting, and migration of configurations.
- [x] [**VSCode Plugin**: Handle reading, writing, and migration of configurations within VSCode.](https://github.com/devchat-ai/devchat/issues/271)
- [x] **JetBrains Plugin**: Manage reading, writing, and migration of configurations within JetBrains IDEs.
- [x] [**devchat-core Adaptation**: Ensure the `devchat-core` codebase supports the new configuration file format.](https://github.com/devchat-ai/devchat/issues/273)

### Objective
The aim is to create a unified configuration management system across different IDEs that improves code maintainability and supports multi-IDE platform operation. Enhancements to VSCode's configuration display and interaction are also critical to providing a more user-friendly experience.

### Expected Outcome
- A shared code logic for configuration management applicable across different IDEs.
- Improved configuration display and interaction within VSCode.
- Seamless configuration migration and management within both VSCode and JetBrains IDEs.

This issue requires careful planning and coordination across different components to ensure a cohesive and fully functioning system. Contributions from individuals with expertise in frontend development, VSCode and JetBrains plugin development, and familiarity with the `devchat-core` codebase are welcome.

**Comment by small-stone** [comment]
Delivered in project gui
