### ISSUE TITLE
The "select all" for checkbox works incorrectly in the Form

### ISSUE THREAD

**Issue by kagami-l** [devchat-ai/devchat#316]
<img width="438" alt="1" src="https://github.com/devchat-ai/devchat/assets/75999237/ab9c8169-b023-4ef6-8eac-99ea0f4bac67">
<img width="539" alt="2" src="https://github.com/devchat-ai/devchat/assets/75999237/dafb7709-70d7-466e-a530-4cc242ed3ec9">

**Comment by small-stone** [comment]
fix in gui e6767697f42d230a4de110dadcb3c1b4675fd07d
