### ISSUE TITLE
请问近期有制作pycharm插件的开发计划嘛？Are there any plans to develop a PyCharm plugin in the near future?

### ISSUE THREAD

**Issue by 5244DragonLin** [devchat-ai/devchat#42]
如题，我的开发环境更多的是是在pycharm下

My development environment is mostly in PyCharm.

**Comment by basicthinker** [comment]
Hi, sorry for the late response. But we at the company don't have a plan for PyCharm yet. The nearest possible timeline should be in six months. Of corse, if community developers make one sometime, that would be best.
