### ISSUE TITLE
devchat key

### ISSUE THREAD

**Issue by luomanman567** [devchat-ai/devchat#43]
您好，请问使用devchat key，调用的是OPENAI API吗？提出相同需求，使用devchat key和使用openai key得到的答复会有区别吗？

Hello, may I ask if the OPENAI API is being called when using the devchat key? If the same request is made, will there be a difference in the response received when using the devchat key versus the openai key?

**Comment by basicthinker** [comment]
DevChat calls OpenAI's API, no matter if you are using OpenAI key or DevChat key.

There is no difference using OpenAI key vs. DevChat key.
