### ISSUE TITLE
After applying diff, the diff tab can be directly closed.

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#51]
<img width="458" alt="image" src="https://github.com/devchat-ai/devchat-vscode/assets/592493/3a2f57a9-f7a6-44fd-9ee5-d7ab5671e368">

==>

<img width="335" alt="image" src="https://github.com/devchat-ai/devchat-vscode/assets/592493/d65ab3e7-d849-4726-a7c8-aef06bd1840d">

---

After using Diff View, modifying the code, and clicking the apply button, there is still an unsaved diff tab. A user then has to click the tab, and close it, with two or three unnecessary clicks. It is best the apply button just applies the code, no matter if it is modified by a user, _and_ always close the diff tab.

**Comment by yangbobo2021** [comment]
问题已经复现并且进行了修复。
