### ISSUE TITLE
Git commit, sync, and check status in one place

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#53]
Git commit, sync (i.e., `git pull; git push`), and check CI status (below) all in DevChat. The CI status may appear around a commit message prompt if a commit or sync is triggered. The source of CI status can be guessed from config files in the repo.

**Comment by runjinz** [comment]
Does this issue still exist? Does it need further attention? If it doesn't require action, please comment to close. @basicthinker
