### ISSUE TITLE
Add action for specified block

### ISSUE THREAD

**Issue by yangbobo2021** [devchat-ai/devchat#59]
I have add two message:
1. regActionList: get all registered actions. result is like: `{command: 'regActionList', result: [{name: '', description: '', type: ['', ''], action: ''}]}`
2. `{command: 'applyAction', actionName: '', codeBlock: { type: '', content: '', fileName: ''}}`. actionName: action user want to apply.

**Comment by runjinz** [comment]
Early feature requirement: dynamically adding buttons, which is no longer needed now.
