### ISSUE TITLE
Failed to install devchat on Win11

### ISSUE THREAD

**Issue by 2016zq** [devchat-ai/devchat#60]
**Describe the bug**
Failed to install devchat on Win11

![670cf5dee789a6fda8ef7bb9b998543](https://github.com/devchat-ai/devchat/assets/17583052/7639f3b0-b6e4-4e00-a0da-82c53f702149)
[cmd_2023-07-08_14.10.13_1_pip_errors.log](https://github.com/devchat-ai/devchat/files/11990275/cmd_2023-07-08_14.10.13_1_pip_errors.log)

[fail.log](https://github.com/devchat-ai/devchat/files/11990276/fail.log)

  157.0ms (setup:799): 2023-07-08 16:43:27
   157.0ms (setup:800): C:\Users\zhaoqiong\AppData\Roaming\Python\Python310\site-packages\pipx\__main__.py environment
   157.0ms (setup:801): pipx version is 1.2.0
   157.0ms (setup:802): Default python interpreter is 'D:\\soft\\python\\python.exe'
   157.0ms (cli:874): pipx finished.

**To Reproduce**
1. sign in https://www.devchat.ai/  and click "this link"
2. Click on "Install" ,
3. Install by default according to prompts

**Expected behavior**
Successfully installed and can be used normally

**Desktop (please complete the following information):**
 - OS: [windows11]
 - Browser [chrome]
 - Version [v0.1.14]

**Additional context**

**Comment by basicthinker** [comment]
It seems the problem is pipx is using a different python interpreter (which is C:\Users\zhaoqiong\.local\pipx\venvs\devchat\Scripts\python.exe) than what is used by your cmd.

Could you rerun `python -m pipx ensurepath` in myenv and then try `pipx install devchat` again?

BTW, why do you issue those commands instead of letting DevChat run the automatic installation process? Does it work? If not, maybe consider uninstalling DevChat and reinstalling it. Our script should be able to handle most issues.

**Comment by yangbobo2021** [comment]
Pipx will use an internal Python interpreter, which is C: Users [...] . Local pipx venvs devchat Scripts Python. exe. All modules installed by pipx will be bound to this interpreter. But when you install pipx and then install devchat through pipx, it will install a Python interpreter with pip module.



In the error log, it is displayed that the pip module does not exist, so some errors occurred during the pipx installation process or devchat installation, and the pip module was not downloaded correctly.



It is recommended to uninstall pipx first, and then manually execute the following command:

Python - m pipx uninstall devchat

Python - m pip install -- user pipx

Python - m pipx securepath

Python - m pipx install devchat -- force
