### ISSUE TITLE
Could not establish a valid connection

### ISSUE THREAD

**Issue by kyriefly** [devchat-ai/devchat#76]
After entering the question in the dialog box, the following error always appears：

Error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.devchat.ai', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

**Comment by yangbobo2021** [comment]
Can you also copy the log output of devchat after vscode is started? Also, do you copy the log output of devchat after clicking the send message button? 
If you click the regenerate button and refresh multiple times, will it be successful?

**Comment by kyriefly** [comment]
已经解决
