### ISSUE TITLE
Decouple DevChat with a workspace in VS Code

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#79]
When I don't open a workspace or a project, the underlying DevChat actually uses the user home folder to create .chat and can work properly. Should we support use of DevChat not in any project/workspace instead of raising the following issue? There are new users who have just installed and started VS Code.
<img width="578" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/9d6142f5-9576-4622-9814-e4fc62300f58">
Can we just set the user settings in this case? Of course, if the user opens a workspace, we can also copy to workspace settings.

**Comment by yangbobo2021** [comment]
This has fixed in pre-release 2023.08.28.
