### ISSUE TITLE
Suggestion for Conda/Mamba/Micromamba Recognition

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#80]
希望能增加对conda或者mamba或者micromamba的虚拟环境管理器的识别

---

I hope DevChat adds recognition for virtual environment managers like conda, mamba, or micromamba.

**Comment by yangbobo2021** [comment]
目前我们打包了mamba环境，默认都是使用mamba来进行虚拟环境安装。如果特殊情况下mamba无法使用，此时会触发conda的使用。
