### ISSUE TITLE
How to set the proxy in Devchat

### ISSUE THREAD

**Issue by Sharkerzhao** [devchat-ai/devchat#84]
How to set the proxy in Devchat?

**Comment by basicthinker** [comment]
Note: This issue and comment only apply to using DevChat's proxy to access OpenAI APIs. If you are directly using OpenAI's endpoint, please skip this.

<img width="338" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/1cdfac9e-f358-4490-b316-197531f8ac89">

In Settings, search "devchat" and set DevChat's API_ENDPOINT to `https://api.devchat.ai/v1`.

<img width="722" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/c933d1cc-e982-4d96-b593-4c418fa941bd">

**Comment by Sharkerzhao** [comment]
Thanks, but that's not what I need.
