### ISSUE TITLE
Remind users of OUTPUT while installing devchat-ask

### ISSUE THREAD

**Issue by basicthinker** [devchat-ai/devchat#97]
<img width="1181" alt="image" src="https://github.com/devchat-ai/devchat/assets/592493/61a9ed9f-28af-43fe-9ea9-bd18f28fa912">

This process really costs a lot of time so it is important to show progress. Can we ensure the following two requirements?
1. As the process starts, can we trigger OUTPUT to show up (no matter if it is a problem or not)?
2. Change the text: `DevChat: Installing devchat-ask. See OUTPUT for progress...`

**Comment by basicthinker** [comment]
@yangbobo2021 apply this to when calling "symbol definitions".

**Comment by basicthinker** [comment]
@yangbobo2021 are the issue and the above comment resolved? If so, please close this.

**Comment by yangbobo2021** [comment]
devchat-ask已经统一到了workflows环境安装中。在vscode启动后，devchat环境检查通过后，开启自动后台安装workflows的虚拟环境。想对来说，不需要太多感知。
